In [1]:
import numpy as np
import pandas as pd

In [10]:
inputfile = './data.csv'
data = pd.read_csv(inputfile)
data

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,y
0,3831732,181.54,448.19,7571.00,6212.70,6370241,525.71,985.31,60.62,65.66,120.0,1.029,5321,64.87
1,3913824,214.63,549.97,9038.16,7601.73,6467115,618.25,1259.20,73.46,95.46,113.5,1.051,6529,99.75
2,3928907,239.56,686.44,9905.31,8092.82,6560508,638.94,1468.06,81.16,81.16,108.2,1.064,7008,88.11
3,4282130,261.58,802.59,10444.60,8767.98,6664862,656.58,1678.12,85.72,91.70,102.2,1.092,7694,106.07
4,4453911,283.14,904.57,11255.70,9422.33,6741400,758.83,1893.52,88.88,114.61,97.7,1.200,8027,137.32
5,4548852,308.58,1000.69,12018.52,9751.44,6850024,878.26,2139.18,92.85,152.78,98.5,1.198,8549,188.14
6,4962579,348.09,1121.13,13966.53,11349.47,7006896,923.67,2492.74,94.37,170.62,102.8,1.348,9566,219.91
7,5029338,387.81,1248.29,14694.00,11467.35,7125979,978.21,2841.65,97.28,214.53,98.9,1.467,10473,271.91
8,5070216,453.49,1370.68,13380.47,10671.78,7206229,1009.24,3203.96,103.07,202.18,97.6,1.560,11469,269.10
9,5210706,533.55,1494.27,15002.59,11570.58,7251888,1175.17,3758.62,109.91,222.51,100.1,1.456,12360,300.55
10,5407087,598.33,1677.77,16884.16,13120.83,7376720,1348.93,4450.55,117.15,249.01,101.7,1.424,14174,338.45
11,5744550,665.32,1905.84,18287.24,14468.24,7505322,1519.16,5154.23,130.22,303.41,101.5,1.456,16394,408.86
12,5994973,738.97,2199.14,19850.66,15444.93,7607220,1696.38,6081.86,128.51,356.99,102.3,1.438,17881,476.72
13,6236312,877.07,2624.24,22469.22,18951.32,7734787,1863.34,7140.32,149.87,429.36,103.4,1.474,20058,838.99
14,6529045,1005.37,3187.39,25316.72,20835.95,7841695,2105.54,8287.38,169.19,508.84,105.9,1.515,22114,843.14
15,6791495,1118.03,3615.77,27609.59,22820.89,7946154,2659.85,9138.21,172.28,557.74,97.5,1.633,24190,1107.67
16,7110695,1304.48,4476.38,30658.49,25011.61,8061370,3263.57,10748.28,188.57,664.06,103.2,1.638,29549,1399.16
17,7431755,1700.87,5243.03,34438.08,28209.74,8145797,3412.21,12423.44,204.54,710.66,105.5,1.670,34214,1535.14
18,7512997,1969.51,5977.27,38053.52,30490.44,8222969,3758.39,13551.21,213.76,760.49,103.0,1.825,37934,1579.68
19,7599295,2110.78,6882.85,42049.14,33156.83,8323096,4454.55,15420.14,228.46,852.56,102.6,1.906,41972,2088.14

In [11]:

data.describe()

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,y
count,2.000000e+01,20.000000,20.000000,20.00000,20.000000,2.000000e+01,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000
mean,5.579520e+06,765.035000,2370.825000,19644.68500,15870.948000,7.350514e+06,1712.239000,5705.799000,129.493500,340.216500,103.305000,1.422200,17273.80000,618.084000
std,1.262195e+06,595.698321,1919.166802,10203.02167,8199.771393,6.213419e+05,1184.713839,4478.400207,50.509834,251.577939,5.513283,0.253235,11109.18894,609.254499
min,3.831732e+06,181.540000,448.190000,7571.00000,6212.700000,6.370241e+06,525.710000,985.310000,60.620000,65.660000,97.500000,1.029000,5321.00000,64.870000
25%,4.525117e+06,302.220000,976.660000,11827.81500,9669.162500,6.822868e+06,848.402500,2077.765000,91.857500,143.237500,99.800000,1.199500,8418.50000,175.435000
50%,5.308896e+06,565.940000,1586.020000,15943.37500,12345.705000,7.314304e+06,1262.050000,4104.585000,113.530000,235.760000,102.450000,1.456000,13267.00000,319.500000
75%,6.594658e+06,1033.535000,3294.485000,25889.93750,21332.185000,7.867810e+06,2244.117500,8500.087500,169.962500,521.065000,103.925000,1.578250,22633.00000,909.272500
max,7.599295e+06,2110.780000,6882.850000,42049.14000,33156.830000,8.323096e+06,4454.550000,15420.140000,228.460000,852.560000,120.000000,1.906000,41972.00000,2088.140000

In [13]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
%matplotlib
Data_ori_1=pd.DataFrame(data.values,index=range(1994,2014),columns=['x1','x2','x3','x4','x5','x6','x7','x8','x9','x10','x11','x12','x13','y'])
Data_y_pic=Data_ori_1['y']
pic_1,axes_4=plt.subplots()
Data_y_pic.plot(ax=axes_4,figsize=(10,8),xticks=range(1994,2014,1),grid=True,style='m*--')
plt.show()

Using matplotlib backend: Qt5Agg

In [15]:
pic_2,axs_3=plt.subplots(figsize=(16,16))
pd.plotting.scatter_matrix(Data_ori_1,ax=axs_3,diagonal='kde',color='#00008B')
plt.show()

In [3]:
np.round(data.corr(method='pearson'),2)

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,y
x1,1.00,0.95,0.95,0.97,0.97,0.99,0.95,0.97,0.98,0.98,-0.29,0.94,0.96,0.94
x2,0.95,1.00,1.00,0.99,0.99,0.92,0.99,0.99,0.98,0.98,-0.13,0.89,1.00,0.98
x3,0.95,1.00,1.00,0.99,0.99,0.92,1.00,0.99,0.98,0.99,-0.15,0.89,1.00,0.99
x4,0.97,0.99,0.99,1.00,1.00,0.95,0.99,1.00,0.99,1.00,-0.19,0.91,1.00,0.99
x5,0.97,0.99,0.99,1.00,1.00,0.95,0.99,1.00,0.99,1.00,-0.18,0.90,0.99,0.99
x6,0.99,0.92,0.92,0.95,0.95,1.00,0.93,0.95,0.97,0.96,-0.34,0.95,0.94,0.91
x7,0.95,0.99,1.00,0.99,0.99,0.93,1.00,0.99,0.98,0.99,-0.15,0.89,1.00,0.99
x8,0.97,0.99,0.99,1.00,1.00,0.95,0.99,1.00,0.99,1.00,-0.15,0.90,1.00,0.99
x9,0.98,0.98,0.98,0.99,0.99,0.97,0.98,0.99,1.00,0.99,-0.23,0.91,0.99,0.98
x10,0.98,0.98,0.99,1.00,1.00,0.96,0.99,1.00,0.99,1.00,-0.17,0.90,0.99,0.99
x11,-0.29,-0.13,-0.15,-0.19,-0.18,-0.34,-0.15,-0.15,-0.23,-0.17,1.00,-0.43,-0.16,-0.12
x12,0.94,0.89,0.89,0.91,0.90,0.95,0.89,0.90,0.91,0.90,-0.43,1.00,0.90,0.87
x13,0.96,1.00,1.00,1.00,0.99,0.94,1.00,1.00,0.99,0.99,-0.16,0.90,1.00,0.99
y,0.94,0.98,0.99,0.99,0.99,0.91,0.99,0.99,0.98,0.99,-0.12,0.87,0.99,1.00

In [4]:
from sklearn.linear_model import Lasso

In [5]:
#调用Lasso函数
lasso = Lasso(1000,random_state=1234)
lasso.fit(data.iloc[:,0:13],data['y'])
np.round(lasso.coef_,5)

D:\software\Anaconda3\lib\site-packages\sklearn\linear_model\coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

array([-1.8000e-04, -0.0000e+00,  1.2414e-01, -1.0310e-02,  6.5400e-02,
        1.2000e-04,  3.1741e-01,  3.4900e-02, -0.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00, -4.0300e-02])

In [6]:
#计算相关系数非0的个数
np.sum(lasso.coef_ != 0)

8

In [7]:
mask =lasso.coef_ != 0

In [8]:
mask

array([ True, False,  True,  True,  True,  True,  True,  True, False,
       False, False, False,  True])

In [9]:
outputfile = './new_reg_data.csv'
new_reg_data = data.iloc[:,mask] #返回相关系数非零的数据
new_reg_data.to_csv(outputfile)
new_reg_data.shape

(20, 8)

In [16]:
new_reg_data

         x1       x3        x4        x5       x6       x7        x8    x13
0   3831732   448.19   7571.00   6212.70  6370241   525.71    985.31   5321
1   3913824   549.97   9038.16   7601.73  6467115   618.25   1259.20   6529
2   3928907   686.44   9905.31   8092.82  6560508   638.94   1468.06   7008
3   4282130   802.59  10444.60   8767.98  6664862   656.58   1678.12   7694
4   4453911   904.57  11255.70   9422.33  6741400   758.83   1893.52   8027
5   4548852  1000.69  12018.52   9751.44  6850024   878.26   2139.18   8549
6   4962579  1121.13  13966.53  11349.47  7006896   923.67   2492.74   9566
7   5029338  1248.29  14694.00  11467.35  7125979   978.21   2841.65  10473
8   5070216  1370.68  13380.47  10671.78  7206229  1009.24   3203.96  11469
9   5210706  1494.27  15002.59  11570.58  7251888  1175.17   3758.62  12360
10  5407087  1677.77  16884.16  13120.83  7376720  1348.93   4450.55  14174
11  5744550  1905.84  18287.24  14468.24  7505322  1519.16   5154.23  16394
12  5994973  2199.14  19850.66  15444.93  7607220  1696.38   6081.86  17881
13  6236312  2624.24  22469.22  18951.32  7734787  1863.34   7140.32  20058
14  6529045  3187.39  25316.72  20835.95  7841695  2105.54   8287.38  22114
15  6791495  3615.77  27609.59  22820.89  7946154  2659.85   9138.21  24190
16  7110695  4476.38  30658.49  25011.61  8061370  3263.57  10748.28  29549
17  7431755  5243.03  34438.08  28209.74  8145797  3412.21  12423.44  34214
18  7512997  5977.27  38053.52  30490.44  8222969  3758.39  13551.21  37934
19  7599295  6882.85  42049.14  33156.83  8323096  4454.55  15420.14  41972

In [17]:
def GM11(x0): #自定义灰色预测函数
    import numpy as np
    x1 = x0.cumsum() #1-AGO序列
    z1 = (x1[:len(x1)-1] + x1[1:])/2.0 #紧邻均值（MEAN）生成序列
    z1 = z1.reshape((len(z1),1))
    B = np.append(-z1, np.ones_like(z1), axis = 1)
    Yn = x0[1:].reshape((len(x0)-1, 1))
    [[a],[b]] = np.dot(np.dot(np.linalg.inv(np.dot(B.T, B)), B.T), Yn) #计算参数
    f = lambda k: (x0[0]-b/a)*np.exp(-a*(k-1))-(x0[0]-b/a)*np.exp(-a*(k-2)) #还原值
    delta = np.abs(x0 - np.array([f(i) for i in range(1,len(x0)+1)]))
    C = delta.std()/x0.std()
    P = 1.0*(np.abs(delta - delta.mean()) < 0.6745*x0.std()).sum()/len(x0)
    return f, a, b, x0[0], C, P #返回灰色预测函数、a、b、首项、方差比、小残差概率

In [23]:
import numpy as np
import pandas as pd
inputfile = './new_reg_data.csv' ##输入的数据文件
inputfile1 = './data.csv' ## 输入的数据文件
new_reg_data = pd.read_csv(inputfile) ## 读取经过特征选择后的数据
data = pd.read_csv(inputfile1) ##读取总的数据
new_reg_data.index = range(1994, 2014)
new_reg_data.loc[2014] = None
new_reg_data.loc[2015] = None
l = ['x1', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x13']
for i in l:
  f = GM11(new_reg_data.loc[range(1994, 2014),i].as_matrix())[0]
  new_reg_data.loc[2014,i] = f(len(new_reg_data)-1)#2014年预测结果
  new_reg_data.loc[2015,i] = f(len(new_reg_data)) ##2015年预测结果
  new_reg_data[i] = new_reg_data[i].round(2) ## 保留两位小数
outputfile = './new_reg_data_GM11.xls' ## 灰色预测后保存的路径
y = list(data['y'].values) ## 提取财政收入列，合并至新数据框中
y.extend([np.nan,np.nan])
new_reg_data['y'] = y
new_reg_data.to_excel(outputfile) ## 结果输出
print('预测结果为：',new_reg_data.loc[2014:2015,:]) ##预测结果展示

预测结果为：       Unnamed: 0          x1       x3        x4        x5          x6  \
2014         NaN  8142148.24  7042.31  43611.84  35046.63  8505522.58
2015         NaN  8460489.28  8166.92  47792.22  38384.22  8627139.31

           x7        x8       x13   y
2014  4600.40  18686.28  44506.47 NaN
2015  5214.78  21474.47  49945.88 NaN

D:\software\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if sys.path[0] == '':

In [31]:
import pandas as pd
import numpy as np
from sklearn.svm import LinearSVR
import matplotlib.pyplot as plt
from sklearn.metrics import explained_variance_score,mean_absolute_error,mean_squared_error,median_absolute_error,r2_score
inputfile = './new_reg_data_GM11.xls' #灰色预测后保存的路径
data = pd.read_excel(inputfile) #读取数据
feature = ['x1', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x13'] 
data.index = data['Unnamed: 0']
data_train = data.loc[range(1994,2014)].copy()#取2014年前的数据建模
data_mean = data_train.mean()
data_std = data_train.std()
data_train = (data_train - data_mean)/data_std #数据标准化
x_train = data_train[feature].as_matrix() #特征数据
y_train = data_train['y'].as_matrix() #标签数据
linearsvr = LinearSVR()   #调用LinearSVR()函数
linearsvr.fit(x_train,y_train)
x = ((data[feature] - data_mean[feature])/ data_std[feature]).as_matrix()  #预测，并还原结果。
data[u'y_pred'] = linearsvr.predict(x) * data_std['y'] + data_mean['y']
## SVR预测后保存的结果
outputfile = './new_reg_data_GM11_revenue.xls'
data.to_excel(outputfile)
print('真实值与预测值分别为：',data[['y','y_pred']])

真实值与预测值分别为：                   y       y_pred
Unnamed: 0
1994          64.87    36.865703
1995          99.75    83.488284
1996          88.11    94.342512
1997         106.07   106.070000
1998         137.32   150.658050
1999         188.14   187.758845
2000         219.91   219.160930
2001         271.91   229.977946
2002         269.10   219.428667
2003         300.55   300.311866
2004         338.45   383.321704
2005         408.86   463.139703
2006         476.72   554.913581
2007         838.99   691.542355
2008         843.14   843.304582
2009        1107.67  1088.209972
2010        1399.16  1379.804756
2011        1535.14  1537.447617
2012        1579.68  1739.967458
2013        2088.14  2086.758450
2014            NaN  2189.360948
2015            NaN  2540.774572

D:\software\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

D:\software\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  from ipykernel import kernelapp as app
D:\software\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
D:\software\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

In [32]:
print('预测图为：',data[['y','y_pred']].plot(subplots = True,
      style=['b-o','r-*']))

预测图为： [<matplotlib.axes._subplots.AxesSubplot object at 0x0000018140B71208>
 <matplotlib.axes._subplots.AxesSubplot object at 0x0000018140DF9358>]

In [28]:
inputfile = './new_reg_data_GM11.xls' #灰色预测后保存的路径
data = pd.read_excel(inputfile) #读取数据
data

,Unnamed: 0,Unnamed: 0.1,x1,x3,x4,x5,x6,x7,x8,x13,y
0,1994,0.0,3831732.00,448.19,7571.00,6212.70,6370241.00,525.71,985.31,5321.00,64.87
1,1995,1.0,3913824.00,549.97,9038.16,7601.73,6467115.00,618.25,1259.20,6529.00,99.75
2,1996,2.0,3928907.00,686.44,9905.31,8092.82,6560508.00,638.94,1468.06,7008.00,88.11
3,1997,3.0,4282130.00,802.59,10444.60,8767.98,6664862.00,656.58,1678.12,7694.00,106.07
4,1998,4.0,4453911.00,904.57,11255.70,9422.33,6741400.00,758.83,1893.52,8027.00,137.32
5,1999,5.0,4548852.00,1000.69,12018.52,9751.44,6850024.00,878.26,2139.18,8549.00,188.14
6,2000,6.0,4962579.00,1121.13,13966.53,11349.47,7006896.00,923.67,2492.74,9566.00,219.91
7,2001,7.0,5029338.00,1248.29,14694.00,11467.35,7125979.00,978.21,2841.65,10473.00,271.91
8,2002,8.0,5070216.00,1370.68,13380.47,10671.78,7206229.00,1009.24,3203.96,11469.00,269.10
9,2003,9.0,5210706.00,1494.27,15002.59,11570.58,7251888.00,1175.17,3758.62,12360.00,300.55
10,2004,10.0,5407087.00,1677.77,16884.16,13120.83,7376720.00,1348.93,4450.55,14174.00,338.45
11,2005,11.0,5744550.00,1905.84,18287.24,14468.24,7505322.00,1519.16,5154.23,16394.00,408.86
12,2006,12.0,5994973.00,2199.14,19850.66,15444.93,7607220.00,1696.38,6081.86,17881.00,476.72
13,2007,13.0,6236312.00,2624.24,22469.22,18951.32,7734787.00,1863.34,7140.32,20058.00,838.99
14,2008,14.0,6529045.00,3187.39,25316.72,20835.95,7841695.00,2105.54,8287.38,22114.00,843.14
15,2009,15.0,6791495.00,3615.77,27609.59,22820.89,7946154.00,2659.85,9138.21,24190.00,1107.67
16,2010,16.0,7110695.00,4476.38,30658.49,25011.61,8061370.00,3263.57,10748.28,29549.00,1399.16
17,2011,17.0,7431755.00,5243.03,34438.08,28209.74,8145797.00,3412.21,12423.44,34214.00,1535.14
18,2012,18.0,7512997.00,5977.27,38053.52,30490.44,8222969.00,3758.39,13551.21,37934.00,1579.68
19,2013,19.0,7599295.00,6882.85,42049.14,33156.83,8323096.00,4454.55,15420.14,41972.00,2088.14
20,2014,NaN,8142148.24,7042.31,43611.84,35046.63,8505522.58,4600.40,18686.28,44506.47,NaN
21,2015,NaN,8460489.28,8166.92,47792.22,38384.22,8627139.31,5214.78,21474.47,49945.88,NaN